友链:
  XAOXUU: https://xaoxuu.com/atom.xml
  LonelyGod: https://hin.cool/atom.xml
  By_Xb: https://byxiaobian.github.io/atom.xml
  枋柚梓的猫会发光: https://raw.githubusercontent.com/inkss/inkss-website/me/atom.xml
  FANTASY: https://blog.tigerxly.com/feed/atom
  HKLin: /friends/HKLin
  7bxing: https://7bxing.com/atom.xml
  bowenyoung: https://raw.githubusercontent.com/BowenYoung/myBlog/main/atom.xml


These Blogs:
  Github: https://github.blog/all.atom
  Cloudflare: https://blog.cloudflare.com/rss/
  RSS3.fun: https://rss3.fun/tag/chinese/rss/

twitter:
  Github: /twitter/user/Github
  Huawei: /twitter/user/HUAWEI
  Cloudflare: /twitter/user/Cloudflare
  CloudflareDev: /twitter/user/CloudflareDev

Github Trending:
  python: /github/trending/daily/python
  javascript: /github/trending/daily/javascript
  any: /github/trending/daily/any


二次元:
  三界异次元: /3ycy/home
  pixiv week: /pixiv/ranking/week
  pixiv day: /pixiv/ranking/day

知乎:
  知乎热榜: /zhihu/hotlist
  机器之心: /zhihu/zhuanlan/jiqizhixin

媒体:
  BBC: /bbc
  华尔街见闻: /wallstreetcn/global
  澎湃新闻: /thepaper/featured
  人民网: /people
  新京报: /bjnews/realtime
  新闻联播: /cctv/xwlb
  中国新闻网: /chinanews
  新浪科技: /sina/discovery/zx
  IT之家: /ithome/ranking/24h
  V2EX: /v2ex/topics/latest
  十年之约: /blogs/foreverblog
  掘金: /juejin/category/article
  开源中国: /oschina/news

发现:
  每日精选: /cnu/selected
  自然: /cnu/discovery/recent/自然
  天文: /bjp/apod
  NASA: /nasa/apod
  1X: /1x
  dailyart: /dailyart/zh
  bing: /bing 

阅读:
  All Poetry: /allpoetry/newest

Status of Monitors: https://rss.uptimerobot.com/u991833-f82a522f0ede9bf2e108279aaf437bcd



